name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  create:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          make -j2
          make dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sys-gdbstub
          path: out/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: out/sys-gdbstub.zip
